import {
  Binary,
  Bot,
  Braces,
  Database,
  FileInput,
  FileOutput,
  Filter,
  GitBranch,
  Globe,
  Sparkles,
} from "lucide-react";
import type { NodeConfig } from "@/types/pipeline";

export const nodeConfigs: NodeConfig[] = [
  {
    type: "customInput",
    title: "Input",
    description: "Pipeline source",
    icon: FileInput,
    category: "input",
    accentColor: "#3b82f6",
    inputs: [],
    outputs: [{ id: "value", label: "value", type: "string" }],
    fields: [
      { name: "inputName", label: "Name", type: "text", defaultValue: "input" },
      {
        name: "inputType",
        label: "Type",
        type: "select",
        defaultValue: "Text",
        options: [
          { label: "Text", value: "Text" },
          { label: "File", value: "File" },
          { label: "URL", value: "URL" },
        ],
      },
    ],
  },
  {
    type: "llm",
    title: "LLM",
    description: "Generate or classify",
    icon: Bot,
    category: "llm",
    accentColor: "#8b5cf6",
    inputs: [
      { id: "system", label: "system", type: "string" },
      { id: "prompt", label: "prompt", type: "string" },
    ],
    outputs: [{ id: "completion", label: "completion", type: "string" }],
    fields: [
      {
        name: "model",
        label: "Model",
        type: "select",
        defaultValue: "gpt-4.1-mini",
        options: [
          { label: "GPT-4.1 mini", value: "gpt-4.1-mini" },
          { label: "GPT-4.1", value: "gpt-4.1" },
          { label: "Claude style mock", value: "mock-claude" },
        ],
      },
      { name: "temperature", label: "Temperature", type: "text", defaultValue: "0.4" },
    ],
  },
  {
    type: "customOutput",
    title: "Output",
    description: "Pipeline destination",
    icon: FileOutput,
    category: "output",
    accentColor: "#22c55e",
    inputs: [{ id: "result", label: "result", type: "string" }],
    outputs: [],
    fields: [
      { name: "outputName", label: "Name", type: "text", defaultValue: "result" },
      {
        name: "format",
        label: "Format",
        type: "select",
        defaultValue: "Text",
        options: [
          { label: "Text", value: "Text" },
          { label: "JSON", value: "JSON" },
          { label: "Markdown", value: "Markdown" },
        ],
      },
    ],
  },
  {
    type: "text",
    title: "Text",
    description: "Template prompt",
    icon: Braces,
    category: "logic",
    accentColor: "#6366f1",
    inputs: [],
    outputs: [{ id: "output", label: "output", type: "string" }],
    fields: [{ name: "text", label: "Text", type: "textarea", defaultValue: "" }],
  },
  {
    type: "custom",
    title: "Custom",
    description: "Reusable placeholder",
    icon: Sparkles,
    category: "data",
    accentColor: "#a855f7",
    inputs: [{ id: "input", label: "input", type: "json" }],
    outputs: [{ id: "output", label: "output", type: "json" }],
    fields: [{ name: "label", label: "Label", type: "text", defaultValue: "Custom step" }],
  },
  {
    type: "api",
    title: "API",
    description: "Fetch external data",
    icon: Globe,
    category: "data",
    accentColor: "#06b6d4",
    inputs: [{ id: "request", label: "request", type: "json" }],
    outputs: [
      { id: "response", label: "response", type: "json" },
      { id: "error", label: "error", type: "string" },
    ],
    fields: [
      {
        name: "method",
        label: "Method",
        type: "select",
        defaultValue: "GET",
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PATCH", value: "PATCH" },
        ],
      },
      {
        name: "endpoint",
        label: "Endpoint",
        type: "text",
        defaultValue: "",
        placeholder: "https://api.example.com",
      },
    ],
  },
  {
    type: "filter",
    title: "Filter",
    description: "Keep matching records",
    icon: Filter,
    category: "logic",
    accentColor: "#f97316",
    inputs: [{ id: "items", label: "items", type: "records" }],
    outputs: [
      { id: "matched", label: "matched", type: "records" },
      { id: "rejected", label: "rejected", type: "records" },
    ],
    fields: [
      {
        name: "condition",
        label: "Condition",
        type: "text",
        defaultValue: "score > 0.8",
      },
    ],
  },
  {
    type: "transform",
    title: "Transform",
    description: "Map data shape",
    icon: Binary,
    category: "logic",
    accentColor: "#14b8a6",
    inputs: [{ id: "input", label: "input", type: "json" }],
    outputs: [{ id: "output", label: "output", type: "json" }],
    fields: [
      {
        name: "operation",
        label: "Operation",
        type: "select",
        defaultValue: "Normalize",
        options: [
          { label: "Normalize", value: "Normalize" },
          { label: "Extract", value: "Extract" },
          { label: "Summarize", value: "Summarize" },
        ],
      },
    ],
  },
  {
    type: "branch",
    title: "Branch",
    description: "Route if / else",
    icon: GitBranch,
    category: "logic",
    accentColor: "#d97706",
    inputs: [{ id: "value", label: "value", type: "json" }],
    outputs: [
      { id: "true", label: "true", type: "json" },
      { id: "false", label: "false", type: "json" },
    ],
    fields: [{ name: "rule", label: "Rule", type: "text", defaultValue: "contains('urgent')" }],
  },
  {
    type: "database",
    title: "Database",
    description: "Read or write records",
    icon: Database,
    category: "data",
    accentColor: "#ec4899",
    inputs: [{ id: "query", label: "query", type: "json" }],
    outputs: [{ id: "records", label: "records", type: "records" }],
    fields: [
      { name: "table", label: "Table", type: "text", defaultValue: "customers" },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        defaultValue: "Read",
        options: [
          { label: "Read", value: "Read" },
          { label: "Write", value: "Write" },
          { label: "Upsert", value: "Upsert" },
        ],
      },
    ],
  },
];

export const nodeConfigByType = new Map(nodeConfigs.map((config) => [config.type, config]));
